title: SynthVerse
description: Exploring the future of technology through AI and blockchain. 
baseurl: "" # 留空
author: Senky
# 导航栏设置
header_pages:
  - index.md
  - about.md
  - contact.md
body {
  background-color: #f0f0f0;
  font-family: Arial, sans-serif;
}
h1, h2 {
  color: #333;
}
